name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

# Pipeline/Workflow Triggers
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  BRANCH_NAME: ${{github.ref_name}}
  IS_TAG: ${{ github.ref_type == 'tag'}}

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: maven settings
        uses: s4u/maven-settings-action@v3.1.0
        with: 
          servers: '[{"id": "nexus-repo", "username": "${{ secrets.NEXUS_USER }}", "password": "${{secrets.EC2_NEXUS_PASSWORD}}"  }]' 
        
      - name: Build IKMDEV Code
        uses: ikmdev/maven-clean-install-build-action@v1.1.0
        with:
          branch_name: ${{env.BRANCH_NAME}}
          
      # - name: Build IKMDEV Code
      #   uses: ikmdev/maven-clean-install-build-action@test
      #   with:
      #     branch_name: ${{env.BRANCH_NAME}}
      #     sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
      #     sonarcloud_host_url: ${{ 'https://sonarcloud.io/' }}
      #     sonarcloud_organization: "ikmdev"
      #     sonarcloud_projectKey: "ikmdev_${{ github.event.repository.name }}"
