name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

on:
  push:
    branches: 
      - main
      - "feature/**"
  pull_request:
      types: 
        - opened
        - synchronize
        - reopened

env:
  BRANCH_NAME: ${{github.ref_name}}

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
    
      - name: Set up Nexus credentials
        env:
          NEXUS_USERNAME: ${{ 'admin' }}
          NEXUS_PASSWORD: ${{ 'Nexusadmin321@' }}
        run: |
          echo "NEXUS_USERNAME=${NEXUS_USERNAME}" >> $GITHUB_ENV
          echo "NEXUS_PASSWORD=${NEXUS_PASSWORD}" >> $GITHUB_ENV

      - name: Download CSV from Nexus
        env:
          NEXUS_USERNAME: ${{ 'admin' }}
          NEXUS_PASSWORD: ${{ 'Nexusadmin321@' }}
        run: |
          # Define variables
          NEXUS_URL="https://nexus.tinkarbuild.com/repository/maven-releases/dev/ikm/data/test_data/1.0/test_data-1.0-dev.ikm.data.csv"
          TARGET_DIR="$GITHUB_WORKSPACE/target"
          echo "CSV_FILE_PATH= $GITHUB_WORKSPACE/target/test_data-1.0-dev.ikm.data.csv" >> $GITHUB_ENV 
          CSV_FILE="test_data-1.0-dev.ikm.data.csv"

          # Create target directory if it doesn't exist
          mkdir -p $TARGET_DIR

          # Download the CSV file
          curl -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" -o "$TARGET_DIR/$CSV_FILE" "$NEXUS_URL"

      - name: Verify CSV download
        run: |
          if [ -f "/home/runner/work/demo-java-maven/demo-java-maven/target/test_data-1.0-dev.ikm.data.csv" ]; then
            echo "CSV file downloaded successfully."
            cat /home/runner/work/demo-java-maven/demo-java-maven/target/test_data-1.0-dev.ikm.data.csv
          else
            echo "CSV file download failed."
            exit 1
          fi
    
      - name: Build IKMDEV Code
        uses: casaras1/maven-clean-install-build-action@main
        with:
          branch_name: ${{env.BRANCH_NAME}}
          sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
          sonarcloud_host_url: ${{ 'https://sonarcloud.io/' }}
          sonarcloud_organization: ${{ github.repository_owner }}
          sonarcloud_sources: ${{ 'src/main/java' }}
          sonarcloud_projectKey: ${{ github.repository_owner }}_${{ github.event.repository.name }}
          sonarcloud_coverage_jacoco_xmlReportPaths: ${{ 'target/site/jacoco/jacoco.xml' }}
          sonarcloud_java_binaries: ${{ 'target/classes' }}
          sonarcloud_tests: ${{ 'src/test/java' }}
          
      # - name: Build IKMDEV Code
      #   uses: ikmdev/maven-clean-install-build-action@test
      #   with:
      #     branch_name: ${{env.BRANCH_NAME}}
      #     sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
      #     sonarcloud_host_url: ${{ 'https://sonarcloud.io/' }}
      #     sonarcloud_organization: "ikmdev"
      #     sonarcloud_projectKey: "ikmdev_${{ github.event.repository.name }}"
