name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

on:
  push:
    branches: 
      - main
      - "feature/**"
  pull_request:
      types: 
        - opened
        - synchronize
        - reopened

env:
  BRANCH_NAME: ${{github.ref_name}}

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: maven settings
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [{
               id: "nexus-repo"
               username: "admin"
               password= "Nexusadmin321@"
            }]   
          
      - name: Build IKMDEV Code
        env:
          NEXUS_USERNAME: ${{ 'admin' }}
          NEXUS_PASSWORD: ${{ 'Nexusadmin321@' }}
          CSV_FILE_PATH: ${{ env.CSV_FILE_PATH }}
          run: |
            if [ -f "/home/runner/work/demo-java-maven/demo-java-maven/target/test_data-1.0-dev.ikm.data.csv" ]; then
              echo "CSV file downloaded successfully."
              cat /home/runner/work/demo-java-maven/demo-java-maven/target/test_data-1.0-dev.ikm.data.csv
            else
              echo "CSV file download failed."
              exit 1
            fi             
        uses: casaras1/maven-clean-install-build-action@main
        with:
          branch_name: ${{env.BRANCH_NAME}}
          sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
          sonarcloud_host_url: ${{ 'https://sonarcloud.io/' }}
          sonarcloud_organization: ${{ github.repository_owner }}
          sonarcloud_sources: ${{ 'src/main/java' }}
          sonarcloud_projectKey: ${{ github.repository_owner }}_${{ github.event.repository.name }}
          sonarcloud_coverage_jacoco_xmlReportPaths: ${{ 'target/site/jacoco/jacoco.xml' }}
          sonarcloud_java_binaries: ${{ 'target/classes' }}
          sonarcloud_tests: ${{ 'src/test/java' }}
          
      # - name: Build IKMDEV Code
      #   uses: ikmdev/maven-clean-install-build-action@test
      #   with:
      #     branch_name: ${{env.BRANCH_NAME}}
      #     sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
      #     sonarcloud_host_url: ${{ 'https://sonarcloud.io/' }}
      #     sonarcloud_organization: "ikmdev"
      #     sonarcloud_projectKey: "ikmdev_${{ github.event.repository.name }}"
