name: Sonar Cloud Demo Build Pipeline

run-name: 'SonarCloud Demo Build Pipeline For ${{github.ref_name}}'

on:
    push:
     branches:
        - "main"
jobs:
  build-job:
    name: Build Job
    runs-on: self-hosted
    steps:
          - name: Checkout Code Repository
            uses: actions/checkout@v4
          - name: Setup Maven Action
            uses: s4u/setup-maven-action@v1.14.0
            with:
                checkout-fetch-depth: 0
                java-version: 21
                java-distribution: adopt
                maven-version: 3.9.0
          - name: Maven Build
            if: github.ref == 'refs/heads/main'
            run: |
              echo 'Running in main branch'
              mvn clean install -PcodeQuality
          - name: Maven Build -- Feature Branch
            if: github.ref != 'refs/heads/main'
            run: |
              echo 'Running in ${{github.ref_name}} branch'
              mvn clean install -PcodeQuality
          - name: Build and analyze
            env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            run: mvn verify sonar:sonar \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.organization=ikmdev \
              -Dsonar.projectKey=ikmdev_demo-java-maven \
              -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
              -Dsonar.junit.reportPath=target/surefire-reports/*HelloTest*.xml \
              -Dsonar.java.binaries=target/classes \
              -Dsonar.sources=src/main/java/ \
              -Dsonar.tests=src/test/java
