on:
  workflow_dispatch:

#    push:
#     branches:
#        - "main"
jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
          sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
          sonarcloud_host_url: ${{ 'https://sonarcloud.io/' }}
          sonarcloud_organization: ${{ github.repository_owner }}
          sonarcloud_sources: src/main/java
          sonarcloud_projectKey: ${{ github.repository_owner }}_${{ github.event.repository.name }}
          sonarcloud_coverage_jacoco_xmlReportPaths: target/site/jacoco/jacoco.xml
          sonarcloud_java_binaries: target/classes
          sonarcloud_tests: src/test/java
          java-version: '21'
          distribution: 'zulu'
      - name: IKMDEV build
        uses: casaras1/maven-clean-install-build-action@main
        with:
          branch_name: ${{env.BRANCH_NAME}}
          
