name: POC Test-Manual

run-name: POC Test-Manual

on:
    - workflow_dispatch

jobs:
    Testing:
        runs-on: self-hosted
        steps:
            - name: Example Step
              run: echo "Instance is up and running!"
            - name: Get code repository
              uses: actions/checkout@v4
            - name: List files
              run: |
                ls ${{github.workspace}}


